#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

task resetIndicate(){
	playTone(1046.5,10);
	stopTask(resetIndicate);
}

void Zelda1()
{
	//        125 = Tempo
	//          5 = Default octave
	//    Quarter = Default note length
	//        10% = Break between notes
	//
	PlayTone(  932,   43); wait1Msec( 480);  // Note(A#)
	PlayTone(  698,   65); wait1Msec( 720);  // Note(F, Duration(Quarter .))
	PlayTone(  932,   22); wait1Msec( 240);  // Note(A#, Duration(Eighth))
	PlayTone(  932,   11); wait1Msec( 120);  // Note(A#, Duration(16th))
	PlayTone(  784,   11); wait1Msec( 120);  // Note(C6, Duration(16th))
	PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
	PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone(    0,   22); wait1Msec( 240);  // Note(Rest, Duration(Eighth))
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone( 1047,   16); wait1Msec( 180);  // Note(F6, Duration(16th .))
	PlayTone( 1109,   11); wait1Msec( 120);  // Note(F#6, Duration(16th))
	PlayTone( 1245,   16); wait1Msec( 180);  // Note(G#6, Duration(16th .))
	PlayTone( 1398,  130); wait1Msec(1440);  // Note(A#6, Duration(Half .))
	PlayTone( 1398,   16); wait1Msec( 180);  // Note(A#6, Duration(16th .))
	PlayTone( 1245,   11); wait1Msec( 120);  // Note(G#6, Duration(16th))
	PlayTone( 1109,   16); wait1Msec( 180);  // Note(F#6, Duration(16th .))
	PlayTone( 1245,   32); wait1Msec( 360);  // Note(G#6, Duration(Eighth .))
	PlayTone( 1109,   16); wait1Msec( 180);  // Note(F#6, Duration(16th .))
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
	PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
	PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
	PlayTone( 1047,   11); wait1Msec( 120);  // Note(F6, Duration(16th))
	PlayTone( 1109,   86); wait1Msec( 960);  // Note(F#6, Duration(Half))
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
	PlayTone(  831,   22); wait1Msec( 240);  // Note(C#6, Duration(Eighth))
	PlayTone(  831,   11); wait1Msec( 120);  // Note(C#6, Duration(16th))
	PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
	PlayTone(  831,   22); wait1Msec( 240);  // Note(C#6, Duration(Eighth))
	PlayTone(  784,   22); wait1Msec( 240);  // Note(C6, Duration(Eighth))
	PlayTone(  784,   11); wait1Msec( 120);  // Note(C6, Duration(16th))
	PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
	PlayTone(  988,   86); wait1Msec( 960);  // Note(E6, Duration(Half))
	PlayTone( 1175,   43); wait1Msec( 480);  // Note(G6)
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  932,   43); wait1Msec( 480);  // Note(A#)
	PlayTone(  698,   65); wait1Msec( 720);  // Note(F, Duration(Quarter .))
	PlayTone(  932,   22); wait1Msec( 240);  // Note(A#, Duration(Eighth))
	PlayTone(  932,   11); wait1Msec( 120);  // Note(A#, Duration(16th))
	PlayTone(  784,   11); wait1Msec( 120);  // Note(C6, Duration(16th))
	PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
	PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone(    0,   22); wait1Msec( 240);  // Note(Rest, Duration(Eighth))
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone( 1047,   16); wait1Msec( 180);  // Note(F6, Duration(16th .))
	PlayTone( 1109,   11); wait1Msec( 120);  // Note(F#6, Duration(16th))
	PlayTone( 1245,   16); wait1Msec( 180);  // Note(G#6, Duration(16th .))
	PlayTone( 1398,  130); wait1Msec(1440);  // Note(A#6, Duration(Half .))
	PlayTone( 1108,   43); wait1Msec( 480);  // Note(C#7)
	PlayTone( 1046,   43); wait1Msec( 480);  // Note(C7)
	PlayTone( 1320,   86); wait1Msec( 960);  // Note(A6, Duration(Half))
	PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
	PlayTone( 1109,  130); wait1Msec(1440);  // Note(F#6, Duration(Half .))
	PlayTone( 1398,   43); wait1Msec( 480);  // Note(A#6)
	PlayTone( 1320,   43); wait1Msec( 480);  // Note(A6)
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
	PlayTone( 1109,  130); wait1Msec(1440);  // Note(F#6, Duration(Half .))
	PlayTone( 1398,   43); wait1Msec( 480);  // Note(A#6)
	PlayTone( 1320,   43); wait1Msec( 480);  // Note(A6)
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone(  880,   43); wait1Msec( 480);  // Note(D6)
	PlayTone(  933,  130); wait1Msec(1440);  // Note(D#6, Duration(Half .))
	PlayTone( 1109,   43); wait1Msec( 480);  // Note(F#6)
	PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
	PlayTone(  831,   86); wait1Msec( 960);  // Note(C#6, Duration(Half))
	PlayTone(  932,   43); wait1Msec( 480);  // Note(A#)
	PlayTone(  784,   43); wait1Msec( 480);  // Note(C6)
	PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
	PlayTone(  988,   86); wait1Msec( 960);  // Note(E6, Duration(Half))
	PlayTone( 1175,   43); wait1Msec( 480);  // Note(G6)
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	return;
}

void ZeldaDung()
{
	//         80 = Tempo
	//          5 = Default octave
	//    Quarter = Default note length
	//        10% = Break between notes
	//
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  932,   17); wait1Msec( 188);  // Note(A#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  932,   17); wait1Msec( 188);  // Note(A#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  932,   17); wait1Msec( 188);  // Note(A#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  932,   17); wait1Msec( 188);  // Note(A#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  739,   17); wait1Msec( 188);  // Note(F#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  739,   17); wait1Msec( 188);  // Note(F#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  739,   17); wait1Msec( 188);  // Note(F#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  739,   17); wait1Msec( 188);  // Note(F#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  698,   17); wait1Msec( 188);  // Note(F, Duration(16th))
	PlayTone(  830,   17); wait1Msec( 188);  // Note(G#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  698,   17); wait1Msec( 188);  // Note(F, Duration(16th))
	PlayTone(  830,   17); wait1Msec( 188);  // Note(G#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  698,   17); wait1Msec( 188);  // Note(F, Duration(16th))
	PlayTone(  830,   17); wait1Msec( 188);  // Note(G#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  698,   17); wait1Msec( 188);  // Note(F, Duration(16th))
	PlayTone(  830,   17); wait1Msec( 188);  // Note(G#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  659,   17); wait1Msec( 188);  // Note(E, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  659,   17); wait1Msec( 188);  // Note(E, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  659,   17); wait1Msec( 188);  // Note(E, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  659,   17); wait1Msec( 188);  // Note(E, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  933,   17); wait1Msec( 188);  // Note(D#6, Duration(16th))
	PlayTone(  622,   17); wait1Msec( 188);  // Note(D#, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  622,   17); wait1Msec( 188);  // Note(D#, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  622,   17); wait1Msec( 188);  // Note(D#, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  622,   17); wait1Msec( 188);  // Note(D#, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  587,   17); wait1Msec( 188);  // Note(D, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  587,   17); wait1Msec( 188);  // Note(D, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  587,   17); wait1Msec( 188);  // Note(D, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  587,   17); wait1Msec( 188);  // Note(D, Duration(16th))
	PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
	PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
	PlayTone(  523,   17); wait1Msec( 188);  // Note(C, Duration(16th))
	PlayTone(  739,   17); wait1Msec( 188);  // Note(F#, Duration(16th))
	PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(16th))
	return;
}

void ZeldaOvrGB()
{
	//        140 = Tempo
	//          5 = Default octave
	//    Quarter = Default note length
	//        10% = Break between notes
	//
	PlayTone(  523,   29); wait1Msec( 321);  // Note(C, Duration(Eighth .))
	PlayTone(  391,   10); wait1Msec( 107);  // Note(G4, Duration(16th))
	PlayTone(  391,   58); wait1Msec( 643);  // Note(G4, Duration(Quarter .))
	PlayTone(  523,   19); wait1Msec( 214);  // Note(C, Duration(Eighth))
	PlayTone(  523,   10); wait1Msec( 107);  // Note(C, Duration(16th))
	PlayTone(  587,   10); wait1Msec( 107);  // Note(D, Duration(16th))
	PlayTone(  622,   10); wait1Msec( 107);  // Note(D#, Duration(16th))
	PlayTone(  698,   10); wait1Msec( 107);  // Note(F, Duration(16th))
	PlayTone(  783,   58); wait1Msec( 643);  // Note(G, Duration(Quarter .))
	PlayTone(  880,   10); wait1Msec( 107);  // Note(A, Duration(16th))
	PlayTone(  932,   10); wait1Msec( 107);  // Note(A#, Duration(16th))
	PlayTone(  880,   29); wait1Msec( 321);  // Note(A, Duration(Eighth .))
	PlayTone(  783,   29); wait1Msec( 321);  // Note(G, Duration(Eighth .))
	PlayTone(  698,   19); wait1Msec( 214);  // Note(F, Duration(Eighth))
	PlayTone(  783,   29); wait1Msec( 321);  // Note(G, Duration(Eighth .))
	PlayTone(  523,   10); wait1Msec( 107);  // Note(C, Duration(16th))
	PlayTone(  784,  154); wait1Msec(1714);  // Note(C6, Duration(Whole))
	PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(Eighth))
	PlayTone(  783,   19); wait1Msec( 214);  // Note(G, Duration(Eighth))
	PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
	PlayTone(  880,   19); wait1Msec( 214);  // Note(D6, Duration(Eighth))
	PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
	PlayTone( 1047,   19); wait1Msec( 214);  // Note(F6, Duration(Eighth))
	PlayTone( 1175,   19); wait1Msec( 214);  // Note(G6, Duration(Eighth))
	PlayTone(  784,   10); wait1Msec( 107);  // Note(C6, Duration(16th))
	PlayTone( 1175,   10); wait1Msec( 107);  // Note(G6, Duration(16th))
	PlayTone( 1046,   58); wait1Msec( 643);  // Note(C7, Duration(Quarter .))
	PlayTone( 1175,   19); wait1Msec( 214);  // Note(G6, Duration(Eighth))
	PlayTone( 1047,   19); wait1Msec( 214);  // Note(F6, Duration(Eighth))
	PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
	PlayTone( 1047,   19); wait1Msec( 214);  // Note(F6, Duration(Eighth))
	PlayTone(  932,   10); wait1Msec( 107);  // Note(A#, Duration(16th))
	PlayTone( 1047,   10); wait1Msec( 107);  // Note(F6, Duration(16th))
	PlayTone( 1398,   58); wait1Msec( 643);  // Note(A#6, Duration(Quarter .))
	PlayTone( 1047,   19); wait1Msec( 214);  // Note(F6, Duration(Eighth))
	PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
	PlayTone(  880,   19); wait1Msec( 214);  // Note(D6, Duration(Eighth))
	PlayTone(  933,   29); wait1Msec( 321);  // Note(D#6, Duration(Eighth .))
	PlayTone(  783,   10); wait1Msec( 107);  // Note(G, Duration(16th))
	PlayTone(  783,   58); wait1Msec( 643);  // Note(G, Duration(Quarter .))
	PlayTone(  783,   10); wait1Msec( 107);  // Note(G, Duration(16th))
	PlayTone(  698,   10); wait1Msec( 107);  // Note(F, Duration(16th))
	PlayTone(  622,   19); wait1Msec( 214);  // Note(D#, Duration(Eighth))
	PlayTone(  698,   19); wait1Msec( 214);  // Note(F, Duration(Eighth))
	PlayTone(  783,  154); wait1Msec(1714);  // Note(G, Duration(Whole))
	PlayTone(  784,   29); wait1Msec( 321);  // Note(C6, Duration(Eighth .))
	PlayTone(  783,   10); wait1Msec( 107);  // Note(G, Duration(16th))
	PlayTone(  783,   58); wait1Msec( 643);  // Note(G, Duration(Quarter .))
	PlayTone(  784,   19); wait1Msec( 214);  // Note(C6, Duration(Eighth))
	PlayTone(  784,   10); wait1Msec( 107);  // Note(C6, Duration(16th))
	PlayTone(  880,   10); wait1Msec( 107);  // Note(D6, Duration(16th))
	PlayTone(  933,   10); wait1Msec( 107);  // Note(D#6, Duration(16th))
	PlayTone( 1047,   10); wait1Msec( 107);  // Note(F6, Duration(16th))
	PlayTone( 1175,   58); wait1Msec( 643);  // Note(G6, Duration(Quarter .))
	PlayTone( 1245,   10); wait1Msec( 107);  // Note(G#6, Duration(16th))
	PlayTone( 1398,   10); wait1Msec( 107);  // Note(A#6, Duration(16th))
	PlayTone( 1245,   19); wait1Msec( 214);  // Note(G#6, Duration(Eighth))
	PlayTone( 1175,   39); wait1Msec( 429);  // Note(G6)
	PlayTone( 1047,   19); wait1Msec( 214);  // Note(F6, Duration(Eighth))
	PlayTone(  933,   29); wait1Msec( 321);  // Note(D#6, Duration(Eighth .))
	PlayTone(  784,   10); wait1Msec( 107);  // Note(C6, Duration(16th))
	PlayTone( 1175,   58); wait1Msec( 643);  // Note(G6, Duration(Quarter .))
	PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
	PlayTone( 1046,   19); wait1Msec( 214);  // Note(C7, Duration(Eighth))
	PlayTone( 1175,   19); wait1Msec( 214);  // Note(G6, Duration(Eighth))
	PlayTone( 1244,   58); wait1Msec( 643);  // Note(D#7, Duration(Quarter .))
	PlayTone( 1174,   19); wait1Msec( 214);  // Note(D7, Duration(Eighth))
	PlayTone( 1046,   19); wait1Msec( 214);  // Note(C7, Duration(Eighth))
	PlayTone( 1174,   19); wait1Msec( 214);  // Note(D7, Duration(Eighth))
	PlayTone( 1244,   19); wait1Msec( 214);  // Note(D#7, Duration(Eighth))
	PlayTone( 1396,   19); wait1Msec( 214);  // Note(F7, Duration(Eighth))
	PlayTone( 1567,   19); wait1Msec( 214);  // Note(G7, Duration(Eighth))
	PlayTone( 1396,   10); wait1Msec( 107);  // Note(F7, Duration(16th))
	PlayTone( 1567,   10); wait1Msec( 107);  // Note(G7, Duration(16th))
	PlayTone( 1661,   58); wait1Msec( 643);  // Note(G#7, Duration(Quarter .))
	PlayTone( 1864,   39); wait1Msec( 429);  // Note(A#7)
	PlayTone( 1661,   19); wait1Msec( 214);  // Note(G#7, Duration(Eighth))
	PlayTone( 1567,   39); wait1Msec( 429);  // Note(G7)
	PlayTone( 1174,   19); wait1Msec( 214);  // Note(D7, Duration(Eighth))
	PlayTone( 1244,   19); wait1Msec( 214);  // Note(D#7, Duration(Eighth))
	PlayTone( 1396,   19); wait1Msec( 214);  // Note(F7, Duration(Eighth))
	PlayTone( 1244,   19); wait1Msec( 214);  // Note(D#7, Duration(Eighth))
	PlayTone( 1174,   19); wait1Msec( 214);  // Note(D7, Duration(Eighth))
	PlayTone( 1046,  116); wait1Msec(1286);  // Note(C7, Duration(Half .))
	return;
}

void mgear()
{
	//        125 = Tempo
	//          5 = Default octave
	//    Quarter = Default note length
	//        10% = Break between notes
	//
	PlayTone(  587,   22); wait1Msec( 240);  // Note(D, Duration(Eighth))
	PlayTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
	PlayTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
	PlayTone(  391,   86); wait1Msec( 960);  // Note(G4, Duration(Half))
	PlayTone(  587,   22); wait1Msec( 240);  // Note(D, Duration(Eighth))
	PlayTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
	PlayTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
	PlayTone(  554,   22); wait1Msec( 240);  // Note(C#, Duration(Eighth))
	PlayTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
	PlayTone(  554,   11); wait1Msec( 120);  // Note(C#, Duration(16th))
	PlayTone(  440,   43); wait1Msec( 480);  // Note(A4)
	PlayTone(  659,   32); wait1Msec( 360);  // Note(E, Duration(Eighth .))
	PlayTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
	PlayTone(  587,   22); wait1Msec( 240);  // Note(D, Duration(Eighth))
	PlayTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
	PlayTone(  554,   11); wait1Msec( 120);  // Note(C#, Duration(16th))
	PlayTone(  523,   43); wait1Msec( 480);  // Note(C)
	PlayTone(  311,   43); wait1Msec( 480);  // Note(D#4)
	PlayTone(  622,   22); wait1Msec( 240);  // Note(D#, Duration(Eighth))
	PlayTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
	PlayTone(  622,   11); wait1Msec( 120);  // Note(D#, Duration(16th))
	PlayTone(  523,   43); wait1Msec( 480);  // Note(C)
	PlayTone(  466,  173); wait1Msec(1920);  // Note(A#4, Duration(Whole))
	PlayTone(  391,   22); wait1Msec( 240);  // Note(G4, Duration(Eighth))
	PlayTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
	PlayTone(  391,   11); wait1Msec( 120);  // Note(G4, Duration(16th))
	PlayTone(  587,   65); wait1Msec( 720);  // Note(D, Duration(Quarter .))
	PlayTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
	PlayTone(  466,   16); wait1Msec( 180);  // Note(A#4, Duration(16th .))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  466,    5); wait1Msec(  60);  // Note(A#4, Duration(32th))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  466,    5); wait1Msec(  60);  // Note(A#4, Duration(32th))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  554,   16); wait1Msec( 180);  // Note(C#, Duration(16th .))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  554,    5); wait1Msec(  60);  // Note(C#, Duration(32th))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  554,   11); wait1Msec( 120);  // Note(C#, Duration(16th))
	PlayTone(  440,   43); wait1Msec( 480);  // Note(A4)
	PlayTone(  659,   43); wait1Msec( 480);  // Note(E)
	PlayTone(  587,   16); wait1Msec( 180);  // Note(D, Duration(16th .))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  554,    5); wait1Msec(  60);  // Note(C#, Duration(32th))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  554,    5); wait1Msec(  60);  // Note(C#, Duration(32th))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  523,   43); wait1Msec( 480);  // Note(C)
	PlayTone(  311,   22); wait1Msec( 240);  // Note(D#4, Duration(Eighth))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  415,    5); wait1Msec(  60);  // Note(G#4, Duration(32th))
	PlayTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
	PlayTone(  622,   11); wait1Msec( 120);  // Note(D#, Duration(16th))
	PlayTone(  698,    5); wait1Msec(  60);  // Note(F, Duration(32th))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  698,    5); wait1Msec(  60);  // Note(F, Duration(32th))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  698,    5); wait1Msec(  60);  // Note(F, Duration(32th))
	PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
	PlayTone(  523,   11); wait1Msec( 120);  // Note(C, Duration(16th))
	PlayTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
	PlayTone(  415,   16); wait1Msec( 180);  // Note(G#4, Duration(16th .))
	PlayTone(  587,  173); wait1Msec(1920);  // Note(D, Duration(Whole))
	return;
}

void smb()
{
	//        100 = Tempo
	//          5 = Default octave
	//    Quarter = Default note length
	//        10% = Break between notes
	//
	PlayTone(  988,   14); wait1Msec( 150);  // Note(E6, Duration(16th))
	PlayTone(  988,   14); wait1Msec( 150);  // Note(E6, Duration(16th))
	PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
	PlayTone(  988,   27); wait1Msec( 300);  // Note(E6, Duration(Eighth))
	PlayTone(  784,   14); wait1Msec( 150);  // Note(C6, Duration(16th))
	PlayTone(  988,   27); wait1Msec( 300);  // Note(E6, Duration(Eighth))
	PlayTone( 1175,   27); wait1Msec( 300);  // Note(G6, Duration(Eighth))
	PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
	PlayTone(  783,   27); wait1Msec( 300);  // Note(G, Duration(Eighth))
	PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
	PlayTone(  784,   27); wait1Msec( 300);  // Note(C6, Duration(Eighth))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  783,   27); wait1Msec( 300);  // Note(G, Duration(Eighth))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  659,   27); wait1Msec( 300);  // Note(E, Duration(Eighth))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  880,   27); wait1Msec( 300);  // Note(A, Duration(Eighth))
	PlayTone(  987,   27); wait1Msec( 300);  // Note(B, Duration(Eighth))
	PlayTone(  932,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
	PlayTone(  880,   27); wait1Msec( 300);  // Note(A, Duration(Eighth))
	PlayTone(  783,   20); wait1Msec( 225);  // Note(G, Duration(16th .))
	PlayTone(  988,   14); wait1Msec( 150);  // Note(E6, Duration(16th))
	PlayTone( 1175,   14); wait1Msec( 150);  // Note(G6, Duration(16th))
	PlayTone( 1320,   27); wait1Msec( 300);  // Note(A6, Duration(Eighth))
	PlayTone( 1047,   14); wait1Msec( 150);  // Note(F6, Duration(16th))
	PlayTone( 1175,   27); wait1Msec( 300);  // Note(G6, Duration(Eighth))
	PlayTone(  988,   27); wait1Msec( 300);  // Note(E6, Duration(Eighth))
	PlayTone(  784,   14); wait1Msec( 150);  // Note(C6, Duration(16th))
	PlayTone(  880,   14); wait1Msec( 150);  // Note(D6, Duration(16th))
	PlayTone(  987,   27); wait1Msec( 300);  // Note(B, Duration(Eighth))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  784,   27); wait1Msec( 300);  // Note(C6, Duration(Eighth))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  783,   27); wait1Msec( 300);  // Note(G, Duration(Eighth))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  659,   27); wait1Msec( 300);  // Note(E, Duration(Eighth))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  880,   27); wait1Msec( 300);  // Note(A, Duration(Eighth))
	PlayTone(  987,   27); wait1Msec( 300);  // Note(B, Duration(Eighth))
	PlayTone(  932,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
	PlayTone(  880,   27); wait1Msec( 300);  // Note(A, Duration(Eighth))
	PlayTone(  783,   20); wait1Msec( 225);  // Note(G, Duration(16th .))
	PlayTone(  988,   14); wait1Msec( 150);  // Note(E6, Duration(16th))
	PlayTone( 1175,   14); wait1Msec( 150);  // Note(G6, Duration(16th))
	PlayTone( 1320,   27); wait1Msec( 300);  // Note(A6, Duration(Eighth))
	PlayTone( 1047,   14); wait1Msec( 150);  // Note(F6, Duration(16th))
	PlayTone( 1175,   27); wait1Msec( 300);  // Note(G6, Duration(Eighth))
	PlayTone(  988,   27); wait1Msec( 300);  // Note(E6, Duration(Eighth))
	PlayTone(  784,   14); wait1Msec( 150);  // Note(C6, Duration(16th))
	PlayTone(  880,   14); wait1Msec( 150);  // Note(D6, Duration(16th))
	PlayTone(  987,   27); wait1Msec( 300);  // Note(B, Duration(Eighth))
	PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
	PlayTone( 1175,   14); wait1Msec( 150);  // Note(G6, Duration(16th))
	PlayTone( 1109,   14); wait1Msec( 150);  // Note(F#6, Duration(16th))
	PlayTone( 1047,   14); wait1Msec( 150);  // Note(F6, Duration(16th))
	PlayTone(  933,   14); wait1Msec( 150);  // Note(D#6, Duration(16th))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  988,   14); wait1Msec( 150);  // Note(E6, Duration(16th))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  830,   14); wait1Msec( 150);  // Note(G#, Duration(16th))
	PlayTone(  880,   14); wait1Msec( 150);  // Note(A, Duration(16th))
	PlayTone(  784,   14); wait1Msec( 150);  // Note(C6, Duration(16th))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  880,   14); wait1Msec( 150);  // Note(A, Duration(16th))
	PlayTone(  784,   14); wait1Msec( 150);  // Note(C6, Duration(16th))
	PlayTone(  880,   14); wait1Msec( 150);  // Note(D6, Duration(16th))
	PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
	PlayTone( 1175,   14); wait1Msec( 150);  // Note(G6, Duration(16th))
	PlayTone( 1109,   14); wait1Msec( 150);  // Note(F#6, Duration(16th))
	PlayTone( 1047,   14); wait1Msec( 150);  // Note(F6, Duration(16th))
	PlayTone(  933,   14); wait1Msec( 150);  // Note(D#6, Duration(16th))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  988,   14); wait1Msec( 150);  // Note(E6, Duration(16th))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone( 1046,   14); wait1Msec( 150);  // Note(C7, Duration(16th))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone( 1046,   14); wait1Msec( 150);  // Note(C7, Duration(16th))
	PlayTone( 1046,   14); wait1Msec( 150);  // Note(C7, Duration(16th))
	PlayTone(    0,   54); wait1Msec( 600);  // Note(Rest)
	PlayTone( 1175,   14); wait1Msec( 150);  // Note(G6, Duration(16th))
	PlayTone( 1109,   14); wait1Msec( 150);  // Note(F#6, Duration(16th))
	PlayTone( 1047,   14); wait1Msec( 150);  // Note(F6, Duration(16th))
	PlayTone(  933,   14); wait1Msec( 150);  // Note(D#6, Duration(16th))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  988,   14); wait1Msec( 150);  // Note(E6, Duration(16th))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  830,   14); wait1Msec( 150);  // Note(G#, Duration(16th))
	PlayTone(  880,   14); wait1Msec( 150);  // Note(A, Duration(16th))
	PlayTone(  784,   14); wait1Msec( 150);  // Note(C6, Duration(16th))
	PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
	PlayTone(  880,   14); wait1Msec( 150);  // Note(A, Duration(16th))
	PlayTone(  784,   14); wait1Msec( 150);  // Note(C6, Duration(16th))
	PlayTone(  880,   14); wait1Msec( 150);  // Note(D6, Duration(16th))
	PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
	PlayTone(  933,   14); wait1Msec( 150);  // Note(D#6, Duration(16th))
	PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
	PlayTone(  880,   14); wait1Msec( 150);  // Note(D6, Duration(16th))
	PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
	PlayTone(  784,   14); wait1Msec( 150);  // Note(C6, Duration(16th))
	return;
}

void Bepis2()
{
	playTone(783.99,12.5); //g
	playTone(659.25,12.5); //e
	playTone(523.25,25); //c
	playTone(523.25,25); //c
	playTone(523.25,12.5); //c
	playTone(587.33,12.5); //d
	playTone(659.25,12.5); //e
	playTone(698.46,12.5); //f
	playTone(783.99,25); //g
	playTone(783.99,25); //g
	playTone(783.99,25); //g
	playTone(659.25,50); //e
}

void Bepis()
{
	playTone(659.25,12.5);
	playTone(783.99,12.5);
	playTone(1046.50,12.5);
	playTone(1318.51,25);
	playTone(1046.50,25);
	playTone(1567.98,50);
	playTone(0,250);
}

int autonSelect = 1; //Default SONG

void pre_auton()
{

	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;

	int countMin = 0;
	int countMax = 10;
	int counter = countMin;
	string str[11] = {"GyroInit","5pt BL/RR","5pt BR/RL","1C High","Stack RL","Stack BR","6","7","8","9","10"}; //Program Names
	bLCDBacklight = true;
	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;

	while(bIfiRobotDisabled == true)
	{

		if(nLCDButtons == 1)
		{
			if(counter == countMin)
			{
				counter = countMax;
			}

			else
			{
				counter--;
			}

			clearLCDLine(0);
			clearLCDLine(1);
			wait1Msec(250);
		}

		else if(nLCDButtons == 4)
		{
			if(counter == countMax)
			{
				counter = countMin;
			}

			else
			{
				counter++;
			}

			clearLCDLine(0);
			clearLCDLine(1);
			wait1Msec(250);
		}

		else if(nLCDButtons == 2)
		{
			clearLCDLine(0);
			clearLCDLine(1);
			if(counter != countMin) autonSelect = counter;
			wait1Msec(250);
			displayLCDCenteredString(0,str[counter]);
			displayLCDCenteredString(1,"Selected!");
			wait1Msec(400);
			clearLCDLine(0);
			clearLCDLine(1);
			wait1Msec(250);
		}

		else
		{
			displayLCDCenteredString(0,str[counter]);
			displayLCDCenteredString(1,"<    Select    >");
		}

	}

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	switch(autonSelect)
	{

	case 1: //


		break;

	case 2: //


		break;

	case 3: //


		break;

	case 4: //


		break;

	case 5: //


		break;

	case 6: //


		break;

	case 7: //


		break;

	case 8: //


		break;

	case 9: //


		break;

	case 10: //


		break;

	}

}

task Horn()
{
	while (1==1)
	{

		if(vexRT[Btn8U] == 1)
		{
			Bepis();
		}

		if(vexRT[Btn8R] == 1)
		{
Zelda1();
		}

		if(vexRT[Btn8D] == 1)
		{
ZeldaDung();
		}

		if(vexRT[Btn8L] == 1)
		{
ZeldaOvrGB();
		}

		if(vexRT[Btn7R] == 1)
		{
smb();
		}

		if(vexRT[Btn7U] == 1)
		{
mgear();
		}

		if(vexRT[Btn7L] == 1)
		{

		}

		if(vexRT[Btn7D] == 1)
		{

		}

		wait1Msec(20);

	}
}



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	startTask(Horn);

}
